@url = https://8080-green-condor-kk1mdctc.ws-us20.gitpod.io
GET {{url}}/filmes

###

POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###

PUT {{url}}/filmes/5
Content-Type: application/json

{
    "titulo" : "GhostBusters"
}

###

DELETE {{url}}/filmes/5
Content-Type: application/json

{
    "id" : 5
}